"""Emit appendix §10 multipanel tables as standalone LaTeX fragments.

Reads ``results/multipanel/summary.json`` plus the VW-NSI cache at
``results/snapshots/nsi_volume_weighted.pkl`` and writes one
``\\input{}``-able fragment per table into ``paper/tables/``:

* ``multipanel_nsi.tex``                -- NSI per (snapshot, N, kind∈{cov,adv}).
* ``multipanel_mutual_dyad.tex``        -- mutual-dyad fraction (%) per cell.
* ``multipanel_zmr.tex``                -- |Z_MR| per cell.
* ``multipanel_jaccard.tex``            -- coverage ∩ ADV overlap per N.
* ``multipanel_runtime.tex``            -- per-job wall-time on M5.
* ``vw_nsi.tex``                        -- volume-weighted NSI vs unweighted at N=500.
* ``multipanel_decile_summary.tex``     -- mean NSI per ADV quintile at N=500.

The appendix `\\input{}`s these so the LaTeX source carries no stale
hardcoded numbers. Run after every multipanel sweep refresh.

Usage::

    .venv/bin/python paper/_generate_multipanel_tables.py
"""
from __future__ import annotations

import json
import pickle
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
MULTI = ROOT / "results" / "multipanel"
SNAP = ROOT / "results" / "snapshots"
TABLES = Path(__file__).resolve().parent / "tables"
TABLES.mkdir(parents=True, exist_ok=True)

PANEL_SIZES = (50, 100, 150, 200, 250, 300, 350, 400, 450, 500)
SNAPSHOTS_ORDERED = [
    "Oct 1987 Black Monday", "1990-91 Recession", "1993 Calm",
    "Dec 1994 Tequila", "Oct 1997 Asian Crisis", "Oct 1998 LTCM",
    "Apr 2000 Dot-com", "Sep 2001 9/11", "Jul 2002 WorldCom",
    "2005 Calm", "2007 Subprime Buildup", "Oct 2008 GFC",
    "Mar 2009 Recovery", "2013 Calm", "2017 Calm",
    "Q4 2018 VolShock", "Mar 2020 COVID", "Jun 2020 Stable",
    "2022 Rate Hikes", "2024 Contemporary",
]


def _load_summary() -> list[dict]:
    path = MULTI / "summary.json"
    assert path.exists(), (
        f"{path} missing; run `python -m tools.run_multipanel --all` first.")
    with open(path) as f:
        return json.load(f)


def _index_records(records, kinds=("coverage", "adv")):
    """Return ``idx[(n, kind)] = record``."""
    out = {}
    for r in records:
        if r["kind"] in kinds:
            out[(r["n"], r["kind"])] = r
    return out


def _row_format(values, fmt):
    """Format a list of (cov, adv) pairs into a LaTeX row body."""
    cells = []
    for cov, adv in values:
        cells.append(fmt(cov))
        cells.append(fmt(adv))
    return " & ".join(cells)


def _fmt_nsi(v):
    return "---" if v is None or (isinstance(v, float) and np.isnan(v)) \
        else f"{v:.3f}"


def _fmt_pct(v):
    return "---" if v is None or (isinstance(v, float) and np.isnan(v)) \
        else f"{v * 100:.1f}"


def _fmt_z(v):
    return "---" if v is None or (isinstance(v, float) and np.isnan(v)) \
        else f"{abs(v):.1f}"


def _fmt_minutes(v):
    return "---" if v is None or (isinstance(v, float) and np.isnan(v)) \
        else f"{v:.1f}"


def _snapshot_label_tex(label):
    """LaTeX-safe label (en-dash, no underscores)."""
    return label.replace("-", "--")


def _emit_master_table(idx, metric_extractor, fmt, *, label, caption,
                       filename, emphasis_cell=None):
    """Emit a 20-snapshot × 10-N × 2-kind master table."""
    col_spec = "@{}l" + "rr" * len(PANEL_SIZES) + "@{}"
    n_header = " & ".join(
        f"\\multicolumn{{2}}{{c}}{{N={n}}}" for n in PANEL_SIZES)
    kind_header = " & ".join(["cov & ADV"] * len(PANEL_SIZES))
    lines = [
        "% AUTOGENERATED by paper/_generate_multipanel_tables.py",
        "% DO NOT EDIT BY HAND; rerun after every multipanel sweep refresh.",
        "\\begin{table}[htbp]",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\centering \\scriptsize \\setlength{\\tabcolsep}{2pt}",
        "\\resizebox{\\textwidth}{!}{%",
        f"\\begin{{tabular}}{{{col_spec}}}",
        "\\toprule",
        "Snapshot & " + n_header + " \\\\",
        " & " + kind_header + " \\\\",
        "\\midrule",
    ]
    for snap in SNAPSHOTS_ORDERED:
        cells = []
        for n in PANEL_SIZES:
            cov_rec = idx.get((n, "coverage"))
            adv_rec = idx.get((n, "adv"))
            cov_val = metric_extractor(cov_rec, snap) if cov_rec else None
            adv_val = metric_extractor(adv_rec, snap) if adv_rec else None
            # Highlight the audit-flagged cells.
            for v, kind in ((cov_val, "coverage"), (adv_val, "adv")):
                s = fmt(v)
                if emphasis_cell and emphasis_cell(snap, n, kind):
                    s = f"\\textbf{{{s}}}"
                cells.append(s)
        lines.append(f"{_snapshot_label_tex(snap):20s} & "
                     + " & ".join(cells) + " \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}}",
        "\\end{table}",
        "",
    ]
    (TABLES / filename).write_text("\n".join(lines), encoding="utf-8")
    print(f"  Wrote {filename}")


def _extract_nsi(rec, snap):
    s = rec["snapshots"].get(snap)
    return s["nsi"] if s else None


def _extract_mut(rec, snap):
    s = rec["snapshots"].get(snap)
    return s["mutual_dyad_fraction"] if s else None


def _extract_zmr(rec, snap):
    s = rec["snapshots"].get(snap)
    return s.get("z_mr") if s else None


def _argmax_nsi_per_snapshot(idx, snap):
    """Return ((n, kind), nsi) for the cell with the largest |NSI - NSI_500_cov|.

    Used by the master tables to bold the audit-flagged extremes.
    """
    base_rec = idx.get((500, "coverage"))
    if not base_rec:
        return None
    base = base_rec["snapshots"].get(snap, {}).get("nsi")
    if base is None:
        return None
    best, best_dev = None, 0.0
    for (n, k), r in idx.items():
        v = r["snapshots"].get(snap, {}).get("nsi")
        if v is None:
            continue
        dev = abs(v - base)
        if dev > best_dev:
            best_dev, best = dev, (n, k, v)
    return best


def emit_nsi_table(records):
    idx = _index_records(records)
    # Bold the per-snapshot largest |NSI - NSI_500_cov| cell.
    extremes = {snap: _argmax_nsi_per_snapshot(idx, snap)
                for snap in SNAPSHOTS_ORDERED}

    def emph(snap, n, kind):
        e = extremes.get(snap)
        return e is not None and (n, kind) == (e[0], e[1])

    _emit_master_table(
        idx, _extract_nsi, _fmt_nsi,
        label="tab:multipanel-nsi",
        caption="Network Stress Index (NSI) across panel sizes and "
                "selection rules (coverage / ADV). Bold cell per row "
                "is the largest |NSI(N,kind) - NSI(500,cov)| deviation.",
        filename="multipanel_nsi.tex",
        emphasis_cell=emph,
    )


def emit_mutual_dyad_table(records):
    idx = _index_records(records)
    _emit_master_table(
        idx, _extract_mut, _fmt_pct,
        label="tab:multipanel-mutual-dyad-fraction",
        caption="Mutual-dyad fraction (\\%) across panel sizes and "
                "selection rules.",
        filename="multipanel_mutual_dyad.tex",
    )


def emit_zmr_table(records):
    idx = _index_records(records)
    _emit_master_table(
        idx, _extract_zmr, _fmt_z,
        label="tab:multipanel-zmr",
        caption="$|Z_\\text{MR}|$ across panel sizes and selection rules.",
        filename="multipanel_zmr.tex",
    )


def emit_jaccard_table(records):
    idx = _index_records(records)
    lines = [
        "% AUTOGENERATED by paper/_generate_multipanel_tables.py",
        "\\begin{table}[htbp]",
        "\\caption{Coverage vs.\\ ADV ticker-set overlap. Jaccard "
        "$=|\\text{cov}\\cap\\text{ADV}|/|\\text{cov}\\cup\\text{ADV}|$.}",
        "\\label{tab:multipanel-jaccard}",
        "\\centering \\small",
        "\\begin{tabular}{@{}rrrrr@{}}",
        "\\toprule",
        "$N$ & $|\\text{cov}|$ & $|\\text{cov}\\cap\\text{ADV}|$ "
        "& Jaccard & $|\\text{cov}\\setminus\\text{ADV}|$ \\\\",
        "\\midrule",
    ]
    for n in PANEL_SIZES:
        cov = idx.get((n, "coverage"))
        adv = idx.get((n, "adv"))
        if not cov or not adv:
            lines.append(f"{n} & --- & --- & --- & --- \\\\")
            continue
        cov_set = set(cov["tickers"])
        adv_set = set(adv["tickers"])
        inter = cov_set & adv_set
        union = cov_set | adv_set
        jaccard = len(inter) / len(union) if union else float("nan")
        only_cov = cov_set - adv_set
        lines.append(
            f"{n} & {len(cov_set)} & {len(inter)} & "
            f"{jaccard:.3f} & {len(only_cov)} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    (TABLES / "multipanel_jaccard.tex").write_text(
        "\n".join(lines), encoding="utf-8")
    print("  Wrote multipanel_jaccard.tex")


def emit_runtime_table(records):
    idx = _index_records(records)
    lines = [
        "% AUTOGENERATED by paper/_generate_multipanel_tables.py",
        "\\begin{table}[htbp]",
        "\\caption{Per-job run-time on M5 (single subprocess) for each "
        "$(N,\\text{kind})$ combination, in minutes. Subprocesses are "
        "spawned fresh per panel (see \\texttt{tools.run\\_multipanel}); "
        "the \\texttt{--workers 8} pool amortises wall-clock by "
        "overlapping panels, but the per-job timings here are the "
        "single-subprocess cost.}",
        "\\label{tab:multipanel-runtime}",
        "\\centering \\small \\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}l" + "r" * len(PANEL_SIZES) + "@{}}",
        "\\toprule",
        " & \\multicolumn{" + str(len(PANEL_SIZES)) + "}{c}{$N$} \\\\",
        f"\\cmidrule(lr){{2-{len(PANEL_SIZES) + 1}}}",
        "Kind & " + " & ".join(str(n) for n in PANEL_SIZES) + " \\\\",
        "\\midrule",
    ]
    for kind, label in (("coverage", "coverage"), ("adv", "ADV")):
        cells = []
        for n in PANEL_SIZES:
            r = idx.get((n, kind))
            cells.append(_fmt_minutes(r["total_minutes"]) if r else "---")
        lines.append(f"{label:10s} & " + " & ".join(cells) + " \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    (TABLES / "multipanel_runtime.tex").write_text(
        "\n".join(lines), encoding="utf-8")
    print("  Wrote multipanel_runtime.tex")


def emit_vw_nsi_table():
    """Volume-weighted vs unweighted NSI at N=500 (coverage panel)."""
    cache = SNAP / "nsi_volume_weighted.pkl"
    s5_cache = SNAP / "stage5_results.pkl"
    if not cache.exists() or not s5_cache.exists():
        print(f"  [warn] {cache.name} or {s5_cache.name} missing -- "
              "vw_nsi.tex skipped")
        return
    with open(cache, "rb") as f:
        vw = pickle.load(f)
    with open(s5_cache, "rb") as f:
        s5 = pickle.load(f)
    unweighted = s5["snapshot_nsi"].set_index("snapshot")["nsi"]
    vw = vw.set_index("snapshot")
    # Order by NSI desc on the unweighted variant for readability.
    ordered = unweighted.sort_values(ascending=False).index.tolist()

    lines = [
        "% AUTOGENERATED by paper/_generate_multipanel_tables.py",
        "\\begin{table}[htbp]",
        "\\caption{Volume-weighted NSI (Stage-5 channels reweighted "
        "by per-snapshot log-ADV) vs.\\ the unweighted paper-canonical "
        "NSI on the twenty-snapshot panel. $\\Delta = "
        "\\mathrm{NSI}_\\text{vw} - \\mathrm{NSI}$.}",
        "\\label{tab:vw-nsi}",
        "\\centering \\small",
        "\\begin{tabular}{@{}lcrrr@{}}",
        "\\toprule",
        "Snapshot & Regime & $\\mathrm{NSI}$ & $\\mathrm{NSI}_\\text{vw}$ "
        "& $\\Delta$ \\\\",
        "\\midrule",
    ]
    for snap in ordered:
        if snap not in vw.index:
            continue
        reg = vw.loc[snap, "regime"]
        nsi_u = float(unweighted.loc[snap])
        nsi_v = float(vw.loc[snap, "nsi_vw"])
        delta = nsi_v - nsi_u
        delta_str = f"$+{delta:.3f}$" if delta > 0 else f"${delta:.3f}$"
        lines.append(
            f"{_snapshot_label_tex(snap):20s} & {reg:9s} & "
            f"{nsi_u:.3f} & {nsi_v:.3f} & {delta_str} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    (TABLES / "vw_nsi.tex").write_text("\n".join(lines), encoding="utf-8")
    print("  Wrote vw_nsi.tex")


def emit_decile_summary_table(records):
    """ADV-quintile cross-section: mean NSI per crisis category.

    For each ``kind`` the row is read from the largest panel size at
    which that cell exists in summary.json. For decile1..5 this is the
    point at which the quintile slice is fully saturated (cap reached);
    for bottom_adv / bottom_coverage the largest available N is the
    most selection-rich tail (smallest gap from full universe is the
    least informative direction, but we report what the sweep has).
    """
    idx_all = {(r["n"], r["kind"]): r for r in records}
    rows = []
    chosen_n = {}
    for kind in ("decile1", "decile2", "decile3", "decile4", "decile5",
                 "bottom_adv", "bottom_coverage"):
        cells = sorted([(n, k) for (n, k) in idx_all if k == kind],
                       key=lambda nk: -nk[0])
        if not cells:
            continue
        n_used = cells[0][0]
        rec = idx_all[(n_used, kind)]
        chosen_n[kind] = n_used
        snaps = rec["snapshots"]
        crisis_nsi = np.mean([snaps[s]["nsi"]
                              for s in ("Oct 2008 GFC", "Mar 2020 COVID")
                              if s in snaps])
        baseline_nsi = np.mean([snaps[s]["nsi"]
                                for s in ("2005 Calm", "2013 Calm",
                                          "2017 Calm",
                                          "2024 Contemporary")
                                if s in snaps])
        stress_2022 = snaps.get("2022 Rate Hikes", {}).get("nsi")
        rows.append((kind, n_used, len(rec["tickers"]),
                     crisis_nsi, baseline_nsi, stress_2022))

    lines = [
        "% AUTOGENERATED by paper/_generate_multipanel_tables.py",
        "\\begin{table}[htbp]",
        "\\caption{Liquidity-decile cross-section. Each row is read "
        "from the largest panel size at which that cell exists in "
        "\\texttt{results/multipanel/summary.json}; the $N$ column "
        "shows that size. A populated ADV decile saturates at "
        "$|\\text{panel}|\\approx\\text{universe}/5$ regardless of $N$; "
        "on the current cache only \\texttt{decile1}--\\texttt{decile4} "
        "carry constituents, while the least-liquid \\texttt{decile5} "
        "and the two bottom-$N$ tail selections return empty panels "
        "($|\\text{panel}|=0$, shown ``---''). "
        "$\\overline{\\text{NSI}}_\\text{crisis}$ averages the two "
        "crisis peaks; $\\overline{\\text{NSI}}_\\text{baseline}$ "
        "averages four calm windows; the 2022 column is the single "
        "2022~Rate~Hikes NSI.}",
        "\\label{tab:multipanel-decile-summary}",
        "\\centering \\small",
        "\\begin{tabular}{@{}lrrrrr@{}}",
        "\\toprule",
        "Selection & $N$ & $|\\text{panel}|$ & "
        "$\\overline{\\text{NSI}}_\\text{crisis}$ & "
        "$\\overline{\\text{NSI}}_\\text{baseline}$ "
        "& NSI(2022) \\\\",
        "\\midrule",
    ]
    pretty = {
        "decile1": "ADV decile 1 (top)",
        "decile2": "ADV decile 2",
        "decile3": "ADV decile 3",
        "decile4": "ADV decile 4",
        "decile5": "ADV decile 5 (bottom)",
        "bottom_adv": "Bottom-N by ADV",
        "bottom_coverage": "Bottom-N by coverage",
    }
    for kind, n_used, npanel, crisis, base, s22 in rows:
        lines.append(
            f"{pretty[kind]} & {n_used} & {npanel} & "
            f"{_fmt_nsi(crisis)} & {_fmt_nsi(base)} & {_fmt_nsi(s22)} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    (TABLES / "multipanel_decile_summary.tex").write_text(
        "\n".join(lines), encoding="utf-8")
    print("  Wrote multipanel_decile_summary.tex")


def _emit_headline_stats(records):
    """Emit small ``\\newcommand``s of headline scalars for paper.tex.

    The macros are ``\\input{}``ed by paper.tex (preamble) so the
    abstract / main-text figures stay in lockstep with the live sweep.
    """
    idx = _index_records(records)
    cov500 = idx.get((500, "coverage"))
    adv500 = idx.get((500, "adv"))
    if not cov500 or not adv500:
        print("  [warn] N=500 coverage/ADV missing -- skipping headline macros")
        return
    cov_set = set(cov500["tickers"])
    adv_set = set(adv500["tickers"])
    inter = cov_set & adv_set
    union = cov_set | adv_set
    jaccard_500 = len(inter) / len(union) if union else float("nan")

    # |Δ NSI| at N=500 across snapshots (largest absolute gap + which snapshot).
    deltas_500 = []
    for snap in SNAPSHOTS_ORDERED:
        cov_v = cov500["snapshots"].get(snap, {}).get("nsi")
        adv_v = adv500["snapshots"].get(snap, {}).get("nsi")
        if cov_v is not None and adv_v is not None:
            deltas_500.append((snap, abs(cov_v - adv_v)))
    if deltas_500:
        max_delta_snap, max_delta_500 = max(deltas_500, key=lambda kv: kv[1])
    else:
        max_delta_snap, max_delta_500 = None, float("nan")

    # Strongest cross-rule deviation at any N (the "largest single deviation"
    # claim in the abstract). Defined as the max over (snapshot, N) of
    # |NSI_cov - NSI_adv|.
    max_dev = (float("nan"), None, None, None, None)
    for n in PANEL_SIZES:
        cov_r = idx.get((n, "coverage"))
        adv_r = idx.get((n, "adv"))
        if not cov_r or not adv_r:
            continue
        for snap in SNAPSHOTS_ORDERED:
            cov_v = cov_r["snapshots"].get(snap, {}).get("nsi")
            adv_v = adv_r["snapshots"].get(snap, {}).get("nsi")
            if cov_v is None or adv_v is None:
                continue
            d = abs(cov_v - adv_v)
            if np.isnan(max_dev[0]) or d > max_dev[0]:
                max_dev = (d, n, snap, cov_v, adv_v)

    lines = [
        "% AUTOGENERATED by paper/_generate_multipanel_tables.py",
        "% Headline multipanel scalars for paper.tex \\input{}.",
        f"\\newcommand{{\\jaccardFiveHundred}}{{{jaccard_500:.3f}}}",
        f"\\newcommand{{\\maxDeltaNSIAtFiveHundred}}{{{max_delta_500:.3f}}}",
        f"\\newcommand{{\\maxDeltaNSIAtFiveHundredSnap}}"
        f"{{{_snapshot_label_tex(max_delta_snap) if max_delta_snap else '---'}}}",
        f"\\newcommand{{\\largestCrossRuleDeviationNSI}}"
        f"{{{max_dev[0]:.3f}}}",
        f"\\newcommand{{\\largestCrossRuleDeviationSnap}}"
        f"{{{_snapshot_label_tex(max_dev[2]) if max_dev[2] else '---'}}}",
        f"\\newcommand{{\\largestCrossRuleDeviationN}}{{{max_dev[1] or '---'}}}",
        "",
    ]
    (TABLES / "multipanel_headline.tex").write_text(
        "\n".join(lines), encoding="utf-8")
    print(f"  Wrote multipanel_headline.tex "
          f"(Jaccard@500={jaccard_500:.3f}, max|Δ|@500={max_delta_500:.3f}, "
          f"largest cross-rule |Δ|={max_dev[0]:.3f} @ N={max_dev[1]}, "
          f"{max_dev[2]})")


def main():
    records = _load_summary()
    n_records = len(records)
    print(f"Loaded {n_records} sweep records from {MULTI / 'summary.json'}")
    print(f"Writing tables to {TABLES}/")
    emit_nsi_table(records)
    emit_mutual_dyad_table(records)
    emit_zmr_table(records)
    emit_jaccard_table(records)
    emit_runtime_table(records)
    emit_decile_summary_table(records)
    emit_vw_nsi_table()
    _emit_headline_stats(records)
    print("Done.")


if __name__ == "__main__":
    main()
