"""
Generators for the new tables and figures added in the 2026-05-27
audit pass:

Tables (paper/tables/):
  - bonf_z_per_snapshot.tex   -- per-snapshot |Z| on Q1 + 3 motif axes
                                  with Bonferroni-10 threshold flag
  - adf_rejection_per_snapshot.tex -- per-snapshot ADF rejection rate
                                       on standardised residuals
  - stage3_sensitivity_grid.tex -- joint (alpha, tau, lag, c_floor)
                                    sweep summary

Figures (paper/figures/):
  - fig_nsi_vix_scatter.pdf   -- 10-point NSI vs window-mean VIX
                                  scatter with OLS line + 95% CI
  - fig_power_mde.pdf         -- exact-permutation p-value lattice
                                  on cohen-d axis (n_crisis = 2 floor)
  - fig_cross_sector_matrix.pdf -- 11x11 sector x sector cross-edge
                                    incidence at the top-k = 4637 budget

Every artefact reads directly from the Stage-1..5 caches and from
results/snapshots/stage1_adf_diagnostics.json so values cannot drift
from the paper's macro file.
"""
import json
import pickle
import sys
from pathlib import Path
from typing import Dict

import matplotlib

matplotlib.use("Agg")
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import norm

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from src.config import SNAPSHOTS  # noqa: E402  (sys.path set just above)

SNAP = ROOT / "results" / "snapshots"
FIG = Path(__file__).resolve().parent / "figures"
TAB = Path(__file__).resolve().parent / "tables"
FIG.mkdir(exist_ok=True)
TAB.mkdir(exist_ok=True)

# Imperial palette mirrors paper/generate_figures.py so the new
# artefacts inherit the same chromatic system.
REGIME_COLORS = {
    "crisis":   "#B2182B",
    "stress":   "#E08214",
    "recovery": "#1A9850",
    "baseline": "#2166AC",
}
IMPERIAL_IVORY    = "#F5E9D7"
IMPERIAL_GOLD_LT  = "#E0B84C"
IMPERIAL_GRAPHITE = "#2A2E33"

plt.rcParams.update({
    "font.family": "serif",
    "font.size": 9,
    "axes.titlesize": 10,
    "axes.labelsize": 9,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "legend.fontsize": 8,
    "figure.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.05,
    "pdf.fonttype": 42,
})

# Snapshot order, short labels, and analysis windows all derive from
# src.config.SNAPSHOTS so this generator can never drift from the panel
# the pipeline actually estimated. The pre-CRSP build pinned a 10-entry
# list here by hand; that is what silently reverted regenerated tables to
# the old universe until 2026-05-29.
_MONTHS = {"Jan", "Feb", "Mar", "Apr", "May", "Jun",
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"}


def _short_label(label: str) -> str:
    """Leading date token(s) of a snapshot label, for tight table/axis text.

    'Oct 1987 Black Monday' -> 'Oct 1987'; '1993 Calm' -> '1993';
    'Q4 2018 VolShock' -> 'Q4 2018'; '1990-91 Recession' -> '1990-91'.
    """
    toks = label.split()
    if toks[0] in _MONTHS or toks[0].startswith("Q"):
        return f"{toks[0]} {toks[1]}"
    return toks[0]


SNAP_ORDER = [s[0] for s in SNAPSHOTS]
SHORT_LABEL = {lab: _short_label(lab) for lab in SNAP_ORDER}
SNAP_WINDOWS = {s[0]: (s[1], s[2]) for s in SNAPSHOTS}

BANNER_HEAD = "% AUTOGENERATED by paper/_generate_extra.py -- do not edit.\n"


# ---------------------------------------------------------------------
# Cache loaders. Asserts give immediate feedback if a generator runs
# on a half-populated cache rather than failing later inside matplotlib.
# ---------------------------------------------------------------------
def _load_stage4():
    with open(SNAP / "stage4_results.pkl", "rb") as fh:
        s4 = pickle.load(fh)
    assert all(s in s4 for s in SNAP_ORDER), "stage4 cache missing snapshots"
    return s4


def _load_stage5():
    with open(SNAP / "stage5_results.pkl", "rb") as fh:
        s5 = pickle.load(fh)
    assert "snapshot_nsi" in s5, "stage5 cache missing snapshot_nsi frame"
    return s5


def _load_adf():
    with open(SNAP / "stage1_adf_diagnostics.json") as fh:
        return json.load(fh)


def _load_stage3_sensitivity():
    with open(SNAP / "stage3_sensitivity.pkl", "rb") as fh:
        return pickle.load(fh)


def _load_vix():
    vix = pd.read_parquet(ROOT / "data" / "vix.parquet")
    if "Close" in vix.columns:
        return vix["Close"].dropna()
    return vix.iloc[:, 0].dropna()


# ---------------------------------------------------------------------
# Table 1: Bonferroni per-snapshot Z on Q1 + three motif axes.
# Two-sided Bonferroni at family size m = len(SNAP_ORDER) (per axis):
# Phi^{-1}(1 - 0.025/m). On the post-CRSP 20-snapshot panel m = 20 and
# the threshold is ~3.023. The Q1 (ER clustering) axis clears on every
# snapshot; >=1 of the three motif axes dips below it on the early-panel windows,
# which are daggered and named in the caption rather than masked (the
# pre-CRSP 10-snapshot panel had no failures, hence the old caption).
# ---------------------------------------------------------------------
def emit_bonf_z_table(out_path):
    s4 = _load_stage4()
    n_fam = len(SNAP_ORDER)
    thr = float(norm.ppf(1 - 0.025 / n_fam))   # per-axis Bonferroni-m

    rows = []
    for label in SNAP_ORDER:
        d = s4[label]
        zc   = abs(d["erdos_renyi"]["z_scores"]["clustering"])
        mo   = d.get("motifs")
        zffl = abs(mo["z_scores"]["feed_forward_loop"]) if mo else float("nan")
        zmr  = abs(mo["z_scores"]["mutual_regulation"])  if mo else float("nan")
        zsim = abs(mo["z_scores"]["single_input_module"]) if mo else float("nan")
        rows.append((label, d["regime"], zc, zffl, zmr, zsim))

    # Q1 (ER clustering) is the panel-wide robust claim: it must clear the
    # threshold on every snapshot. The motif axes are permitted to fall
    # below on sparse windows; those cells are daggered, not masked.
    for label, _r, zc, *_ in rows:
        assert zc > thr, (
            f"clustering |Z_C|={zc:.2f} at {label} fell below the "
            f"Bonferroni-{n_fam} threshold {thr:.3f}; the panel-wide Q1 "
            "claim no longer holds -- revise the prose, do not mask it."
        )

    # Catalogue cells below the threshold and the single smallest |Z|
    # across all 4*m axis-snap pairs, for a data-driven caption.
    axis_sym = {"Q1": "|Z_C|", "FFL": "|Z_\\text{FFL}|",
                "MR": "|Z_\\text{MR}|", "SIM": "|Z_\\text{SIM}|"}
    cells = [(label, ax, v)
             for (label, _r, zc, zffl, zmr, zsim) in rows
             for ax, v in (("Q1", zc), ("FFL", zffl),
                           ("MR", zmr), ("SIM", zsim))
             if np.isfinite(v)]
    fail_snaps = sorted({label for label, _ax, v in cells if v <= thr},
                        key=SNAP_ORDER.index)
    gmin = min(cells, key=lambda t: t[2])
    zc_lo = min(r[2] for r in rows)
    zc_hi = max(r[2] for r in rows)
    fail_names = ", ".join(SHORT_LABEL[L].replace(" ", "~") for L in fail_snaps)

    out = [BANNER_HEAD]
    out.append(f"% Bonferroni-{n_fam} per-snapshot |Z| table.\n")
    out.append("\\begin{table}[htbp]\n")
    out.append("\\caption{Per-snapshot $|Z|$ on the Q1 (ER clustering) "
               "and three motif axes against the per-axis "
               f"Bonferroni-{n_fam} two-sided threshold "
               f"$|Z|>\\Phi^{{-1}}(1{{-}}0.025/{n_fam})\\approx {thr:.3f}$ "
               "($\\dagger$ marks cells below it). Q1 clears on every "
               f"snapshot ($|Z_C|\\in[{zc_lo:.2f},\\,{zc_hi:.2f}]$), while "
               "at least one of the three motif axes dips below the "
               f"threshold on the early-panel windows {fail_names}; the smallest cell is "
               f"${axis_sym[gmin[1]]}={gmin[2]:.2f}$ at "
               f"{gmin[0].replace(' ', '~')}, the minimum across all "
               f"{len(cells)} axis--snap pairs. Auto-extracted from "
               "\\texttt{stage4\\_results.pkl}.}\n")
    out.append("\\label{tab:bonf-z-per-snapshot}\n")
    out.append("\\centering\n")
    out.append("\\small\n")
    out.append("\\rowcolors{2}{imperialCream}{white}\n")
    out.append("\\begin{tabular}{@{}llrrrr@{}}\n")
    out.append("\\toprule\n")
    out.append("Snapshot & Regime & $|Z_C|$ & $|Z_\\text{FFL}|$ & "
               "$|Z_\\text{MR}|$ & $|Z_\\text{SIM}|$ \\\\\n")
    out.append("\\midrule\n")

    def _cell(v):
        if not np.isfinite(v):
            return "{--}"
        return f"{v:.2f}$^\\dagger$" if v <= thr else f"{v:.2f}"

    for label, regime, zc, zffl, zmr, zsim in rows:
        out.append(
            f"{SHORT_LABEL[label]:<10s} & {regime:<8s} & "
            f"{_cell(zc)} & {_cell(zffl)} & {_cell(zmr)} & {_cell(zsim)} \\\\\n"
        )
    out.append("\\bottomrule\n")
    out.append("\\end{tabular}\n")
    out.append("\\end{table}\n")
    out_path.write_text("".join(out), encoding="utf-8")
    print(f"  wrote {out_path} ({out_path.stat().st_size:,} bytes)")


# ---------------------------------------------------------------------
# Table 2: ADF rejection rate per snapshot on standardised residuals.
# ---------------------------------------------------------------------
def emit_adf_table(out_path):
    adf = _load_adf()
    alpha = adf["alpha"]
    full = adf["full_panel"]
    per = adf["per_snapshot"]

    # Caption facts derived from the data, not hardcoded: the lowest-power
    # window (shortest test span) and the panel year range.
    floor_label = min(per, key=lambda k: per[k]["reject_rate"])
    floor_rate = per[floor_label]["reject_rate"] * 100.0
    # 1985 = CRSP standardised-residual burn-in start (precedes the first
    # snapshot window); the end year tracks the latest snapshot in config.
    span = f"1985--{max(s[2] for s in SNAPSHOTS)[:4]}"

    out = [BANNER_HEAD]
    out.append("\\begin{table}[htbp]\n")
    out.append("\\caption{Augmented Dickey--Fuller rejection rate on the "
               "standardised residuals $z_{i,t}$ entering Stage~1c, per "
               f"snapshot window and across the full {span} post-CRSP "
               f"sample, at $\\alpha={alpha}$. Short snapshots have shorter "
               "test windows and therefore lower power; the floor on "
               f"this panel is ${floor_rate:.1f}\\%$ at "
               f"{floor_label.replace(' ', '~')}. "
               "$n_\\text{tested}$ is the per-asset count with enough "
               "standardised residuals for the test, slightly above the "
               "per-window $\\geq 80\\%$-coverage alive count because the "
               "ADF screen is per asset rather than complete-case. "
               "Auto-extracted "
               "from \\texttt{stage1\\_adf\\_diagnostics.json}.}\n")
    out.append("\\label{tab:adf-rejection-per-snapshot}\n")
    out.append("\\centering\n")
    out.append("\\small\n")
    out.append("\\rowcolors{2}{imperialCream}{white}\n")
    out.append("\\begin{tabular}{@{}lrrr@{}}\n")
    out.append("\\toprule\n")
    out.append("Window & $T$ (days) & $n_\\text{tested}$ & "
               "Reject rate \\\\\n")
    out.append("\\midrule\n")
    for label in SNAP_ORDER:
        row = per[label]
        out.append(
            f"{SHORT_LABEL[label]:<10s} & {row['n_days']:>5d} & "
            f"{row['n_tested']:>5d} & {row['reject_rate']*100:5.1f}\\% \\\\\n"
        )
    out.append("\\midrule\n")
    out.append(
        f"Full sample {span} & {full['n_days']:>5d} & "
        f"{full['n_tested']:>5d} & {full['reject_rate']*100:5.1f}\\% \\\\\n"
    )
    out.append("\\bottomrule\n")
    out.append("\\end{tabular}\n")
    out.append("\\end{table}\n")
    out_path.write_text("".join(out), encoding="utf-8")
    print(f"  wrote {out_path} ({out_path.stat().st_size:,} bytes)")


# ---------------------------------------------------------------------
# Table 3: Stage-3 joint sensitivity grid summary.
# Each row of the grid is a cell in (alpha, tau, lag, c_floor); we
# report the crisis-vs-non-crisis mean mutual-fraction gap.
# ---------------------------------------------------------------------
def emit_stage3_sensitivity_table(out_path):
    s = _load_stage3_sensitivity()
    grid = s["grid"]
    headline = s["headline_cell"]

    out = [BANNER_HEAD]
    out.append("\\begin{table}[htbp]\n")
    out.append("\\caption{Stage-3 joint "
               "$\\alpha\\times\\tau\\times\\text{lag}\\times c_\\text{floor}$ "
               "sensitivity grid (14 cells). Each cell records crisis-mean "
               "and non-crisis-mean mutual-dyad fraction and their gap; "
               "the headline cell is bold. Crisis $f_\\text{mut}$ stays "
               "above non-crisis on every cell in the sweep. Auto-extracted "
               "from \\texttt{results/snapshots/stage3\\_sensitivity.pkl}.}\n")
    out.append("\\label{tab:stage3-sensitivity}\n")
    out.append("\\centering\n")
    out.append("\\small\n")
    out.append("\\rowcolors{2}{imperialCream}{white}\n")
    out.append("\\begin{tabular}{@{}rrrrrrr@{}}\n")
    out.append("\\toprule\n")
    out.append("$\\alpha$ & $\\tau$ & lag & $c_\\text{floor}$ & "
               "$\\overline{f}_\\text{mut}^\\text{cris}$ & "
               "$\\overline{f}_\\text{mut}^\\text{ncri}$ & "
               "$\\Delta$ \\\\\n")
    out.append("\\midrule\n")
    for cell in grid:
        key = (cell["alpha"], cell["tau"],
               cell["granger_lag"], cell["granger_floor"])
        cm = cell["crisis_mean_mutual_fraction"]
        nm = cell["noncrisis_mean_mutual_fraction"]
        gap = cm - nm
        bold = (key == tuple(headline))
        fmt = "\\textbf{%s}" if bold else "%s"
        out.append(
            f"{fmt % f'{key[0]:.2f}'} & "
            f"{fmt % f'{key[1]:.1f}'} & "
            f"{fmt % str(key[2])} & "
            f"{fmt % f'{key[3]:.1f}'} & "
            f"{fmt % f'{cm:.3f}'} & "
            f"{fmt % f'{nm:.3f}'} & "
            f"{fmt % f'{gap:+.3f}'} \\\\\n"
        )
    out.append("\\bottomrule\n")
    out.append("\\end{tabular}\n")
    out.append("\\end{table}\n")
    out_path.write_text("".join(out), encoding="utf-8")
    print(f"  wrote {out_path} ({out_path.stat().st_size:,} bytes)")


# ---------------------------------------------------------------------
# Figure 1: NSI vs window-mean VIX scatter with OLS line + 95% CI.
# Uses the same data as fig5_nsi_vix_overlay but renders the correlation
# directly so the reader can verify Pearson r visually.
# ---------------------------------------------------------------------
def figure_nsi_vix_scatter(out_path):
    s5 = _load_stage5()
    nsi = s5["snapshot_nsi"].copy()
    nsi = nsi.set_index("snapshot").reindex(SNAP_ORDER).reset_index()
    vix_s = _load_vix()
    # Window-mean VIX over each snapshot's own estimation window (from
    # config), so the scatter cannot drift from the panel.
    win_vix = []
    for lbl in nsi["snapshot"]:
        a, b = SNAP_WINDOWS[lbl]
        s = vix_s.loc[a:b]
        win_vix.append(float(s.mean()))
    nsi["vix_mean"] = win_vix

    x = nsi["vix_mean"].to_numpy()
    y = nsi["nsi"].to_numpy()
    assert len(x) == len(SNAP_ORDER) and len(y) == len(SNAP_ORDER), \
        f"NSI-VIX scatter expects {len(SNAP_ORDER)} points"

    # OLS regression line + analytic 95% prediction band on the mean.
    slope, intercept = np.polyfit(x, y, deg=1)
    resid = y - (slope * x + intercept)
    n = len(x)
    s2 = float(np.sum(resid ** 2)) / max(1, n - 2)
    xbar = float(np.mean(x))
    sxx = float(np.sum((x - xbar) ** 2))
    xx = np.linspace(x.min() - 1, x.max() + 1, 200)
    se = np.sqrt(s2 * (1.0 / n + (xx - xbar) ** 2 / sxx))
    from scipy.stats import t as student_t
    tcrit = float(student_t.ppf(0.975, df=n - 2))
    yy = slope * xx + intercept

    r = float(np.corrcoef(x, y)[0, 1])

    fig, ax = plt.subplots(figsize=(5.2, 4.0))
    ax.fill_between(xx, yy - tcrit * se, yy + tcrit * se,
                    color=IMPERIAL_GOLD_LT, alpha=0.22, zorder=1,
                    label="OLS 95% mean-band")
    ax.plot(xx, yy, color=IMPERIAL_GRAPHITE, linewidth=1.4, zorder=2,
            label=f"OLS  NSI = {slope:.3f}$\\cdot$VIX + {intercept:.2f}")

    for _, row in nsi.iterrows():
        c = REGIME_COLORS[row["regime"]]
        ax.scatter(row["vix_mean"], row["nsi"], s=65, color=c,
                   edgecolor=IMPERIAL_GRAPHITE, linewidth=0.7, zorder=4)
        ax.annotate(SHORT_LABEL[row["snapshot"]],
                    (row["vix_mean"], row["nsi"]),
                    xytext=(5, 3), textcoords="offset points",
                    fontsize=6.8, color=IMPERIAL_GRAPHITE)

    ax.set_xlabel("Window-mean VIX", fontweight="bold")
    ax.set_ylabel("Snapshot NSI", fontweight="bold")
    ax.set_title(f"NSI vs. VIX (snapshot, $n={len(SNAP_ORDER)}$): "
                 f"Pearson $r = {r:.3f}$", fontweight="bold")
    ax.grid(linestyle=":", linewidth=0.4, alpha=0.5)
    ax.set_axisbelow(True)

    # Regime legend.
    legend_handles = [mpatches.Patch(color=c, label=k.capitalize())
                      for k, c in REGIME_COLORS.items()]
    ax.legend(handles=legend_handles, loc="lower right",
              fontsize=7, frameon=True, framealpha=0.95,
              facecolor=IMPERIAL_IVORY, edgecolor=IMPERIAL_GOLD_LT,
              ncol=2)

    fig.tight_layout()
    fig.savefig(out_path)
    fig.savefig(out_path.with_suffix(".png"), dpi=300)
    plt.close(fig)
    print(f"  wrote {out_path} ({out_path.stat().st_size:,} bytes)")


# ---------------------------------------------------------------------
# Figure 2: Exact-permutation power lattice. The null has C(N, k) parts
# for N = len(SNAP_ORDER) snapshots and k crisis windows (post-CRSP:
# C(20, 7) = 77,520, hard floor 1/77,520 ~ 1.3e-5). Every
# positively-deviating headline metric (Cohen's d > 0) is plotted at its
# observed (d, p) from inference_macros.tex against the p = 0.05 / 0.10
# reference lines and the floor. The metric membership is read from the
# macros, so a sign change (e.g. the HHI un-reversal under CRSP) flows
# through automatically rather than via a hand-edited inclusion list.
# ---------------------------------------------------------------------
def figure_power_mde(out_path):
    from math import comb

    n_snap = len(SNAP_ORDER)
    n_crisis = sum(1 for s in SNAPSHOTS if s[3] == "crisis")
    n_part = comb(n_snap, n_crisis)
    floor = 1.0 / n_part

    macros_path = ROOT / "paper" / "output" / "inference_macros.tex"
    macros = {}
    if macros_path.exists():
        import re
        macro_re = re.compile(r"\\newcommand\{\\([A-Za-z]+)\}\{([^}]*)\}")
        for line in macros_path.read_text(encoding="utf-8").splitlines():
            mm = macro_re.match(line.strip())
            if mm:
                macros[mm.group(1)] = mm.group(2)

    metrics = [
        ("Mut.-dyad frac.",   "DMutDyad", "PMutDyad"),
        ("PageRank Gini",     "DGini",    "PGini"),
        ("Mean $\\bar\\rho$", "DMeanRho", "PMeanRho"),
        ("Cross-sec. edges",  "DCrossSec", "PCrossSec"),
        ("$|Z_\\text{MR}|$",  "DZMR",     "PZMR"),
        ("PageRank HHI",      "DHHI",     "PHHI"),
        ("NSI",               "DNSI",     "PNSI"),
    ]
    pts = []
    for label, dk, pk in metrics:
        dv = macros.get(f"Inf{dk}")
        pv = macros.get(f"Inf{pk}")
        if dv is None or pv is None:
            continue
        try:
            d, p = float(dv), float(pv)
        except ValueError:
            continue
        if d > 0:                       # positively-deviating metrics only
            pts.append((label, d, p))
    assert pts, "no positively-deviating inference macros for the MDE figure"
    pts.sort(key=lambda t: t[1])        # by d, for stable label placement

    fig, ax = plt.subplots(figsize=(5.4, 4.0))

    # p = 0.05 / 0.10 reference lines.
    for thr_p, lab, ls in [(0.05, r"$p=0.05$", "--"),
                           (0.10, r"$p=0.10$", ":")]:
        ax.axhline(thr_p, color=REGIME_COLORS["crisis"],
                   linewidth=0.9, linestyle=ls, alpha=0.85)
        ax.text(0.015, thr_p + 0.006, lab, fontsize=7,
                color=REGIME_COLORS["crisis"], va="bottom")

    # Hard floor at 1/C(N, k). On the 20-snapshot panel this is ~1.3e-5,
    # far below every observed p: the binding constraint is now the data,
    # not the partition count (the opposite of the old 10-snapshot panel,
    # whose 1/45 floor sat among the observations).
    exp = int(np.floor(np.log10(floor)))
    mant = floor / 10 ** exp
    n_part_tex = f"{n_part:,}".replace(",", "{,}")
    ax.axhline(floor, color=REGIME_COLORS["recovery"],
               linewidth=0.9, linestyle="-", alpha=0.9)
    ax.text(0.015, floor + 0.004,
            rf"hard floor $1/\binom{{{n_snap}}}{{{n_crisis}}}="
            rf"1/{n_part_tex}\approx {mant:.1f}\times10^{{{exp}}}$",
            fontsize=7, color=REGIME_COLORS["recovery"], va="bottom")

    for i, (label, d, p) in enumerate(pts):
        ax.scatter(d, p, s=70, color=REGIME_COLORS["baseline"],
                   edgecolor=IMPERIAL_GOLD_LT, linewidth=0.9, zorder=5)
        dy = 11 if (i % 2 == 0) else -17
        ax.annotate(label, (d, p), xytext=(6, dy),
                    textcoords="offset points", fontsize=7.0,
                    color=IMPERIAL_GRAPHITE,
                    bbox=dict(boxstyle="round,pad=0.18",
                              facecolor=IMPERIAL_IVORY,
                              edgecolor="none", alpha=0.92))

    pmax = max(p for _l, _d, p in pts)
    ax.set_xlabel("Cohen's $d$  (crisis vs. non-crisis)", fontweight="bold")
    ax.set_ylabel("Exact-permutation $p$", fontweight="bold")
    ax.set_title(f"Power lattice: positively-deviating metrics on the "
                 f"$\\binom{{{n_snap}}}{{{n_crisis}}}={n_part_tex}$ null",
                 fontweight="bold")
    ax.set_xlim(left=0)
    ax.set_ylim(-0.01, max(0.40, pmax * 1.18))
    ax.grid(linestyle=":", linewidth=0.4, alpha=0.45)
    ax.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(out_path)
    fig.savefig(out_path.with_suffix(".png"), dpi=300)
    plt.close(fig)
    print(f"  wrote {out_path} ({out_path.stat().st_size:,} bytes)")


# ---------------------------------------------------------------------
# Figure 3: 11x11 sector x sector cross-edge heatmap at the top-k=4637
# budget, averaged across the two crisis snapshots. Diagonal = within-
# sector edges; off-diagonal = cross-sector pair incidence.
# ---------------------------------------------------------------------
def figure_cross_sector_matrix(out_path):
    s4 = _load_stage4()
    info = pd.read_parquet(ROOT / "data" / "sp500_info.parquet")
    sector_of = dict(zip(info["Symbol"], info["GICS Sector"]))
    sectors = sorted(set(info["GICS Sector"].dropna()))
    n_s = len(sectors)
    idx_of = {s: i for i, s in enumerate(sectors)}

    # Pool the two crisis-peak Stage-3 graphs (rounded to the top-4637
    # edges by |partial correlation| each). For each kept edge increment
    # the sector-pair cell.
    crisis_labels = ["Oct 2008 GFC", "Mar 2020 COVID"]
    mat = np.zeros((n_s, n_s), dtype=float)
    for lbl in crisis_labels:
        d = s4[lbl]
        G = d["graph"]
        tickers = d["tickers"]
        # All edges with weights; pick top-4637.
        edges = []
        for u, v in G.edges():
            w = abs(G[u][v].get("weight", 1.0))
            edges.append((u, v, w))
        edges.sort(key=lambda t: t[2], reverse=True)
        edges = edges[:4637]
        for u, v, _w in edges:
            tu = tickers[u] if u < len(tickers) else None
            tv = tickers[v] if v < len(tickers) else None
            su = sector_of.get(tu)
            sv = sector_of.get(tv)
            if su is None or sv is None:
                continue
            i = idx_of[su]; j = idx_of[sv]
            mat[i, j] += 1
    # Row-normalise so each row sums to 1 (read as "given the source
    # sector, where do its outgoing edges land?").
    row_sums = mat.sum(axis=1, keepdims=True)
    row_sums[row_sums == 0] = 1.0
    norm_mat = mat / row_sums

    fig, ax = plt.subplots(figsize=(6.2, 5.4))
    im = ax.imshow(norm_mat, cmap="viridis", vmin=0, vmax=0.45, aspect="auto")
    ax.set_xticks(range(n_s))
    ax.set_xticklabels([s.replace(" ", "\n", 1) for s in sectors],
                       rotation=70, ha="right", fontsize=7)
    ax.set_yticks(range(n_s))
    ax.set_yticklabels(sectors, fontsize=7.5)
    # Outline the diagonal (within-sector cells).
    for i in range(n_s):
        ax.add_patch(plt.Rectangle((i - 0.5, i - 0.5), 1, 1,
                                   fill=False,
                                   edgecolor=IMPERIAL_GOLD_LT,
                                   linewidth=1.0))
    ax.set_xlabel("Target sector", fontweight="bold")
    ax.set_ylabel("Source sector", fontweight="bold")
    ax.set_title("Cross-sector edge incidence at top-$k{=}4637$ "
                 "(crisis-peak pool)", fontweight="bold")
    cb = plt.colorbar(im, ax=ax, shrink=0.85)
    cb.set_label("Row-normalised incidence", fontweight="bold")
    fig.tight_layout()
    fig.savefig(out_path)
    fig.savefig(out_path.with_suffix(".png"), dpi=300)
    plt.close(fig)
    print(f"  wrote {out_path} ({out_path.stat().st_size:,} bytes)")


def main():
    print("[extra] tables...")
    emit_bonf_z_table(TAB / "bonf_z_per_snapshot.tex")
    emit_adf_table(TAB / "adf_rejection_per_snapshot.tex")
    emit_stage3_sensitivity_table(TAB / "stage3_sensitivity_grid.tex")
    print("[extra] figures...")
    # NSI-VIX scatter: paper.tex uses _generate_addon_assets.py's
    # fig_app_nsi_vix_scatter.pdf (NSI on x, VIX on y, cluster-bootstrap
    # CI annotation), so this generator does not write its own scatter.
    # Cross-sector matrix: appendix.tex uses
    # _generate_addon_assets.py's per-snapshot 3-panel
    # fig_app_sector_heatmap.pdf (more informative than the single-panel
    # pooled-crisis variant prototyped here), so this generator does
    # not write its own matrix.
    figure_power_mde(FIG / "fig_power_mde.pdf")
    print("[extra] done.")


if __name__ == "__main__":
    main()
